### ISSUE TITLE
1st content from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#20]
Okay alex here is the content that I created for the website it will go from the top down to the bottom, and as I progress my questions will also progress in that order. 

For this there are little bubbles with a picture graphic, is there a way to make those picture graphics appropriate to the content it is representing? As well as appropriate to the business? 
WHAT WE OFFER
WISE seeks to improve the way you see the ocean through our 4 pillars Education, Travel, Exploration, and Customer Service 

Education 
	We believe Knowledge is power and the more you have the happier and the more confident you will be. 

Travel
	We love travel, and believe that travel can be life affirming and life changing. 

Exploration 
	We know that exploration opens eyes the the light of what once seemed to have been old and dull, to being exciting and invigorating again. 

Customer Service
	To us is as valuable and as important as family, we will always strive to treat you right and always strive to give our very best. 

** can you place these in this order CEET please and the four pillars 

WISE SCUBA 
Improving the way the world learns to dive

OUR CLASSES 
Expect the very best pre-class preparation from our students to assist in the development of our divers into confident underwater enthusiasts, eager to dive and explore often the underwater world. 

ABOUT US
WISE was born on a plane ride traveling back fro the East Coast. With the goal in mind of changing the way the world learning to dive. Starting with the local community then the west coast then the though out the world, helping people develop greater confidence about the ocean though ocean education & exploration. And so the four pillars where born Customer Service, Education, Exploration, and Travel. 

Insta twitter and FB feeds* will go here, and I think for now the claims section will be removed. 
I know I still need to get those passwords to you. speaking of did you get the calendar gmail passwords I sent over in a previous email. 

OUR MISSION 
	To achieve our goals starts with 

Expecting the best 
Innovative teaching Methods 
Quality Training 
Inspiring students 
Sharing Knowledge 
Travel 
Exploration 

THE TEAM
The Picture I would like to try and use first is below other wise I can try for a different one. 
Kristin Green 
	Became a scuba Instructor in 13’ after she fell into scuba in 11’. She became impassioned with the sport, and having the heart of a teacher wanted to share the love of scuba and the ocean with others. 
	She founded WISE in 13’ and slowly progressed WISE and herself to where both are today. Kristin herself is always learning and trying to grow herself in the sport and hopes to  pass on that same desire to her students, and those she meets. 

Bitwise
	I would like for you to put a little blip about yourselves on the site as you said that you are my back offie and I would like to recognize your efforts, if you want. you don have to but I think it would be interesting to see how it looks and what the response would be. if you don't want to, once again I totally understand no harm no foul. 

The questions section is the last place I have a question, how will that work? is my email linked up there or do I need to sign up for something else in order to make that feature work? 

I look forward to seeing this on the site and what it will look like to see if I need to add more or less and see if things need to be moved around or not. 

QUESTION 
Has the email situation been resolved? it looks like maybe but wanted to follow up. 
AND have you tried embedding in the youtube videos? how has that been working as I haven’t seen any up yet? 

thank you again for all that you all have been doing! I appreciate you and your team very much. 

due
11-4-15   5p

updated due:
11-10-15  11a

![964748_10151708290417502_1406385781_o](https://cloud.githubusercontent.com/assets/539962/10894743/40a020a4-8165-11e5-9fe5-5fca55c1fffb.jpg)
![pa160731 copy](https://cloud.githubusercontent.com/assets/539962/10894742/409cefd8-8165-11e5-8432-0e10028a17e2.jpeg)

**Comment by rodneystrong** [comment]
Hey meg, just followin up on this. Let me know what's up please? 
I want to send the client an update today at 4p.

**Comment by vanderbeam** [comment]
This is "Item #1" today. I'm getting my day organized right now and then I'll set this to "In-Progress"

**Comment by vanderbeam** [comment]
I uploaded the content; I've only edited the major typos, my priority was to get all the initial content on the page before proofing. Got a little hung up on the calendar thing. 

QUESTIONS/COMMENTS:
- I just put some lorem in for the Edit blurb. I figured you guys would give me something if you wanted to go ahead and have it on there. 
- She asks about "the question section"... does she mean the Contact info (which I still need so I can input it). 
- She mentions YouTube videos. I scanned the previous issues and couldn't find any links. I figured I would put them where the "claims" section is under the About Me, which is currently blank because she requested it to be take off for the time being.
- She mentions she has an Instagram. I did a couple quick searched on instagram and couldn't find it so I need that link, also.
- She wanted the icons to be approate to the subject, but to her business as well. I used icons I thought represented the idea she was conveying (travel/exploration/.etcetera) but Font Awesome doesn't really have any icons that relate to scuba or water or diving
- There was that fish picture that wasn't really designated so I used it to replace the background on the testimonials because that background of buildings was really bugging me since it didn't fit.
- She didn't give a one liner for "Get in Touch" I can put some generic "WE WANT TO HEAR FROM YOU!" type sentence in there or take the sentence out (which in retrosect I should have just done and then added this question)

**Comment by rodneystrong** [comment]
Here's my video feedback: http://somup.com/coXQYkqdd

I'll check for the youtube links. In the mean time, do me a favor and search youtube for "wise scuba" and see if you can find it. 

Actually nevermind I just did it and found her: https://www.youtube.com/channel/UCNSEIu0XmhUSVYVIxwn9G7w

I'll look for her instagram. 

For the icons.. crap. I'll look into it.

**Comment by rodneystrong** [comment]
Updated the due date to 11-10-15   11a

**Comment by rodneystrong** [comment]
In my video review, I commented about the facebook feed or "like us on facebook" that was missing. I just re-read the fact that it's supposed to be a facebook feed widget right there. Ignore my feedback in the video about that. I just realized she hadn't given us the passwords for those accounts so we could get the API keys and embed their widgets.

**Comment by vanderbeam** [comment]
@rodneystrong What do you think of these? http://depositphotos.com/24156773/stock-illustration-diving-icons-set-elegant-series.html

**Comment by vanderbeam** [comment]
So I pushed the corrections. 
It was always my intentions to put the YouTube video in that blank area next to the Facebook widget. I had previously assumed there was a specific video she'd wanted for the site so since that was not the case I just picked the one that had all the pretty sealife in it. Kinda like, "Hey! You could be seeing this stuff up close and personal!" 
I am not a fan of the photo up in her face like that. I feel like she chose that photo for the entire thing. It has a beautiful background and her scuba gear next to her. Her face is mostly covered, also. She's very pretty so I think if she wanted a picture just for her face she would have given us one that had more face actually in it. I think it would be cool to get her YouTube channel picture if that's actually her. it's too small to tell: 
![wisescuba](https://cloud.githubusercontent.com/assets/12962001/11054490/a01afab0-8721-11e5-8872-62f60c0423d5.jpg)

Now that's a neat pic. 
Her facebook page link is coming up with a "Sorry, this content isn't available right now: The link you followed may have expired, or the page may only be visible to an audience you're not in." error. Is her facebook page set to private?
Lastly, the map.... the map works perfectly for me locally and viewing it from GitHub. I also asked Joel to see if it showed up for him and it did. Everything looks fine in the code for the map so it must have just been a glitch. 
I commented out the street address until we have it and set the long/lat to just Fresno. 

I would like to note though, I'd like to add some more content as far as whereabouts go. As someone who knows nothing about this business besides it is a scuba institution, I'm really curious as to her process, which leads me to believe others will be, also. I mean.... we live in the central valley. When I think scuba diving this is probably one of the last places that comes to mind when i think of prime diving locations. Where do these classes take place? Does she start in Fresno and then take a van full of students to the coast? She talks enough about travel and exploration and such, I can only imagine it's something along those lines. No where on the site does she mention anywhere she actually takes students diving or anything about Fresno, not even in the testimonials (though I did look back in the calendar and checked the events from January. Even those locations are all over Fresno). Honestly if I were looking for a diving class I would probably find it a little vague and therefor sketchy... but that's just my suggestion.

**Comment by rodneystrong** [comment]
Heard back from the client! 

Go ahead and download those icons and see if you can incorporate a few of them into the site. 

We got the facebook issue resovled.

**Comment by vanderbeam** [comment]
Hey Alex, Let me know what you think of the scuba icons
Under "WHAT WE OFFER" the icons... I got them to do the same effect at the first icons that were there, but sometimes they got a little wonky. So I'm working on that. I'm also trying to figure out why the little dot won't go to the right. 

Just giving you an update in case you didn't like the icons.

**Comment by rodneystrong** [comment]
Nice
Did you FTP it ?

**Comment by vanderbeam** [comment]
@rodneystrong OK, I pushed to ftp.

**Comment by rodneystrong** [comment]
dude, good fuckin job with these icons. props. i saw how you fixed the layout issue too
